### ISSUE TITLE
Limitations and Performance implications?

### ISSUE THREAD

**Issue by tejacques** [krzkaczor/babel-plugin-proxy#1]
Would it be possible to have list of limitations and possibly add some benchmarks comparing it to raw property access and to implementations of proxy?

Specifically, does this work?

proxied.js

``` .js
export default new Proxy({}, {
    get: function(target, propKey) {
        if (!(propKey in target)) {
            console.log("Accessing undefined key!");
        }

        return target[propKey];
    }
});
```

tester.js

``` .js
import proxied from './proxied';
proxy.a = 'foo';
console.log(proxy.a);
console.log(proxy.b);
```

e.g. does the plugin work across modules if it knows something is a proxied object?

Does it work for this?

someFunction.js

``` .js
export default function someFunction(someObject) {
    console.log(someObject.a);
}
```

tester2.js

``` .js
import proxied from './proxied';
import someFunction from './someFunction';
someFunction(proxied);
someFunction({ a: 'works?' });
```

The only way I can imagine that working is it if rewrites every single property access in the source code, even for vanilla objects. The performance of that would definitely be pretty sad.

**Comment by krzkaczor** [comment]
All of this examples should work (i didn't test these particular cases). Plugin replaces all member accesses (dots ;) ) in your code into invocation of interceptor functions which checks (in runtime) if object is proxy.
