### ISSUE TITLE
get problem

### ISSUE THREAD

**Issue by willin** [krzkaczor/babel-plugin-proxy#2]
``` js
const proxy = new Proxy({}, {
  get: (target, property) =>
    (test) => [target, property, test]
});

console.log(proxy.func);          // [Function]
console.log(proxy.func('123'));   // TypeError: proxy.func is not a function
```

**Comment by krzkaczor** [comment]
I just fixed it. The problem is half of a year ago I couldn't find an easy way to make it work with methods (missing context) so I skipped them entirely. Now I solved it in like 5 minutes xD 

btw. your example found its place in tests ;)

**Comment by willin** [comment]
i've tried and it works now.
thx a lot
